// GENERATED by `.claude/charpilot/record.mjs --emit-tests` (stage 5) - do not hand-edit.
//
// The config this corpus is meant to be run under, committed beside it:
//
//     npx vitest run --config test/characterization/vitest.config.mts
//
// It extends no root config (see below),
// and resolves modules exactly as the RECORDING did: the recorder's alias
// table and merge, rendered below from its own code, over whatever the root
// declares. It overrides only what a recorded row needs: the corpus as the
// include, and no setup file, because the recording ran with none.
//
// It deliberately imports NOTHING from `.claude/` - repos gitignore that
// directory, so anything there is missing on a pushed branch. Each spec also
// carries its own env prelude for the same reason, which is why no env file is
// read here.
//
// Not type-checked: importing the root config by its `.mts` name is TS5097
// under a tsconfig without allowImportingTsExtensions, and outreach-thread-ms's
// `tsc --noEmit` covers test/. Vitest loads it either way.
// @ts-nocheck
import { resolve } from "node:path";
import { defineConfig } from "vitest/config";

// The root config here is the one install.sh BOOTSTRAPPED, which a branch may not
// carry (finish.py leaves it off until the suite holds a passing test), so this
// corpus does not extend it: it stands alone.
const baseConfig = {};

// ---- charpilot resolution (rendered from .claude/charpilot/resolution.mjs - the recorder's own) ----
const PILOT_ALIAS_TABLE = [
  { find: /^@\/prisma$/, to: "prisma/client", dir: false },
  { find: /^@\/prisma\//, to: "prisma", dir: true },
  { find: /^@\/env$/, to: "src/env", dir: false },
  { find: /^@\//, to: "src", dir: true },
  { find: /^src\//, to: "src", dir: true },
];
function pilotAliases(root, table = PILOT_ALIAS_TABLE) {
  return table.map((e) => ({ find: e.find, replacement: e.dir ? `${resolve(root, e.to)}/` : resolve(root, e.to) }));
}
function asAliasArray(alias) {
  if (!alias) return [];
  if (Array.isArray(alias)) return alias;
  return Object.entries(alias).map(([find, replacement]) => ({ find, replacement }));
}
function literalPrefixLength(find) {
  if (typeof find === "string") return find.length;
  const src = typeof find?.source === "string" ? find.source : "";
  let n = 0;
  for (let i = src.startsWith("^") ? 1 : 0; i < src.length; i++) {
    const c = src[i];
    // An escaped character is one literal character: `\/` in `/^@\//` is `/`.
    if (c === "\\") {
      if (i + 1 >= src.length) break;
      i++;
      n++;
      continue;
    }
    // The first metacharacter ends the fixed prefix. `/` is NOT one.
    if ("^$.*+?()[]{}|".includes(c)) break;
    n++;
  }
  return n;
}
function mergeAliases(hostAlias, pilot) {
  return [...asAliasArray(hostAlias), ...pilot]
    .map((entry, index) => ({ entry, index, prefix: literalPrefixLength(entry.find) }))
    .sort((a, b) => b.prefix - a.prefix || a.index - b.index)
    .map((e) => e.entry);
}
function replayAliases(hostAlias, root) {
  return mergeAliases(hostAlias, pilotAliases(root));
}
const REPLAY_TEST_ENV = {"NODE_ENV":"test","TZ":"UTC"};
// ---- end charpilot resolution ----

export default defineConfig({
  ...baseConfig,
  resolve: { ...baseConfig.resolve, alias: replayAliases(baseConfig.resolve?.alias, resolve(__dirname, "..", "..")) },
  test: {
    ...baseConfig.test,
    setupFiles: [],
    exclude: [],
    // REPO-RELATIVE, because vitest resolves `include` against its own root -
    // the project root, never the config file's directory. `*.char.test.ts`
    // matched nothing and the runner exited 1 on "No test files found", which
    // reads as a red suite rather than as a config that looked in the wrong
    // place.
    include: ["test/characterization/*.char.test.ts"],
    testTimeout: 120_000,
    hookTimeout: 120_000,
    env: { ...(baseConfig.test?.env ?? {}), ...REPLAY_TEST_ENV },
  },
});
