/**
 * THE CHECK THAT RUNS THE CORPUS.
 *
 *   node .claude/charpilot/cicheck.mjs [--write]
 *
 * THE DEFECT THIS EXISTS FOR. The suite this pipeline exists to produce was the
 * one suite the target's CI did not run. notification-ms declares
 * `include: ["tests/**\/*.test.ts"]` and the corpus lands in
 * `test/characterization/` - singular - so `npm test` never matched it. Its
 * workflow says, in a comment, "Runs the Vitest unit/characterization suite on
 * PRs", and it ran neither. A run whose emitted suite failed 41 of 87 tests
 * therefore opened a pull request showing a GREEN `test` check, and the green
 * was true of the pre-existing suite and said nothing about the diff.
 *
 * WHY A SECOND WORKFLOW AND NOT A ONE-LINE `include`. Adding the corpus to the
 * target's own config edits a file their team maintains, and it moves the
 * numbers `vitest.active.config.ts` sets coverage thresholds against
 * (statements 90.03, branches 82.78, functions 96.4) - so the corpus would
 * start deciding whether an unrelated pull request passes. A separate check
 * fails on its own and takes nothing with it.
 *
 * WHY A COPY OF THEIR OWN WORKFLOW. The setup a repo needs to run vitest is
 * not guessable: notification-ms wants `npm ci` and `npx prisma generate` on
 * node 20 with recursive submodules, and the next repo will want something
 * else. Their test workflow already states it. So this copies that file and
 * changes three things - the workflow name, the job key, and the command -
 * which keeps the setup correct by construction and keeps this tool out of the
 * business of knowing how 16 repos build.
 *
 * WHAT IT REFUSES, and each refusal leaves CI exactly as it was:
 *
 *   - no `.github/workflows/`: nothing here creates a CI system for a repo
 *     that has none, because a workflow nobody asked for is a change to how
 *     their repo builds;
 *   - no workflow that runs the test script;
 *   - a candidate with more than one job, since the rewrite below is textual
 *     and cannot tell which job of several is the one that tests;
 *   - a candidate that does not trigger on `pull_request`, because the check
 *     has to appear on the pull request this run opens;
 *   - an existing `characterization.yml` without this tool's marker, which is
 *     then somebody's own file and is left alone.
 *
 * A refusal is a written reason on stdout and exit 0. The corpus is still
 * emitted, the pull request is still opened, and `report.mjs` carries the
 * reason - the honest version of the same fact the green check was hiding.
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

import { CORPUS_REL, REPO_ROOT } from "./config.mjs";

const ARGV = process.argv.slice(2);
const WRITE = ARGV.includes("--write");

const WORKFLOWS = join(REPO_ROOT, ".github", "workflows");
const TARGET = join(WORKFLOWS, "characterization.yml");
export const MARKER = "# GENERATED by .claude/charpilot/cicheck.mjs";
/**
 * The command the check runs, and it names NOTHING under `.claude/`.
 *
 * WHAT THIS USED TO BE: `npm run test:characterization`, whose script body is
 * `vitest run --config .claude/charpilot/vitest.coverage.config.mts`. The
 * target's `.gitignore` ignores `.claude`, so zero files from there reach the
 * pushed branch, and both pull requests this tool has opened failed identically:
 *
 *   Could not resolve ".claude/charpilot/vitest.coverage.config.mts"
 *
 * The check could not pass on any repo. It passed in a local working tree only
 * because the toolset is installed on disk there.
 *
 * TWO REASONS IT IS THE COMMAND AND NOT AN npm SCRIPT. The config now ships
 * with the corpus, so nothing needs to be installed for the check to work; and
 * `install.sh` merges `charpilotScripts` without replacing a key the target
 * already has, so a repo carrying the OLD `test:characterization` would keep
 * pointing at the gitignored path no matter what this tool wrote.
 */
export const COMMAND = `npx vitest run --config ${CORPUS_REL}/vitest.config.mts`;
export const SCRIPT = COMMAND;

/**
 * The one job in `text`, or null if it does not have exactly one.
 *
 * Textual on purpose: a YAML parser is not in this pipeline's dependencies and
 * adding one to rewrite three lines would be the larger change. The cost is
 * that this understands only the shape every one of these workflows has -
 * `jobs:` at column 0, job keys at two spaces - and REFUSES anything else
 * rather than guessing.
 */
export function soleJob(text) {
  const lines = text.split("\n");
  const at = lines.findIndex((l) => /^jobs:\s*$/.test(l));
  if (at === -1) return null;
  const keys = [];
  for (const line of lines.slice(at + 1)) {
    if (/^\S/.test(line)) break;
    const m = line.match(/^ {2}([A-Za-z_][\w-]*):\s*$/);
    if (m) keys.push(m[1]);
  }
  return keys.length === 1 ? keys[0] : null;
}

/** Whether `text` triggers on pull_request, in either of the two forms. */
export function onPullRequest(text) {
  const at = text.split("\n").findIndex((l) => /^on:/.test(l));
  if (at === -1) return false;
  const lines = text.split("\n");
  if (/^on:\s*\[.*pull_request.*\]/.test(lines[at])) return true;
  for (const line of lines.slice(at + 1)) {
    if (/^\S/.test(line)) break;
    if (/^\s{2,}pull_request\s*:?\s*$/.test(line)) return true;
    if (/^\s*-\s*pull_request\s*$/.test(line)) return true;
  }
  return false;
}

/**
 * The line that runs the repo's tests, or null.
 *
 * `npm test`, `npm run test`, `yarn test`, `pnpm test` - and NOT
 * `npm run test:coverage` or any other suffixed script, which is a different
 * suite with different thresholds. The boundary is asserted in the tests
 * because getting it wrong means rewriting the wrong line of somebody's CI.
 */
export function testRunLine(text) {
  const lines = text.split("\n");
  for (let i = 0; i < lines.length; i++) {
    // `- run:` as well as `run:`. A step with no `name:` is written
    // `- run: npm test`, and the first version of this anchored on `run:` at
    // the start of the line - so it read notification-ms, whose step is named,
    // and would have missed every repo that writes the short form.
    if (/^\s*(?:-\s+)?run:\s*(npm|yarn|pnpm)\s+(run\s+)?test\s*$/.test(lines[i])) return i;
  }
  return null;
}

/** The candidate workflow, or a written reason why there is none. */
export function pick(files) {
  const reasons = [];
  for (const { name, text } of files) {
    if (text.includes(MARKER)) continue;
    if (testRunLine(text) === null) continue;
    const job = soleJob(text);
    if (!job) {
      reasons.push(`${name} runs the test script but does not have exactly one job, so which job tests is not answerable textually`);
      continue;
    }
    if (!onPullRequest(text)) {
      reasons.push(`${name} runs the test script in one job but does not trigger on pull_request, so a copy of it would not appear on the pull request`);
      continue;
    }
    return { name, text, job };
  }
  return { reason: reasons.length ? reasons.join("; ") : null };
}

/** The candidate, rewritten to run the corpus instead. */
export function rewrite({ name, text, job }) {
  const lines = text.split("\n");
  const run = testRunLine(text);
  lines[run] = lines[run].replace(/(?:npm|yarn|pnpm)\s+(?:run\s+)?test\s*$/, COMMAND);
  // The step's own name, if it has one, so the log does not say "Run tests"
  // over a different suite.
  for (let i = run; i >= 0 && i > run - 4; i--) {
    if (/^\s*-?\s*name:\s*/.test(lines[i])) {
      lines[i] = lines[i].replace(/name:.*$/, "name: Run the characterization corpus");
      break;
    }
  }
  const head = lines.findIndex((l) => /^name:/.test(l));
  if (head !== -1) {
    lines[head] = "name: Characterization";
    // The comment block under the original `name:` describes the ORIGINAL
    // workflow, and copying it into this file makes this file lie. On
    // notification-ms it read "Runs the Vitest unit/characterization suite on
    // PRs", which is the exact false claim this tool exists to stop repeating.
    // Contiguous comments and blanks only, so nothing structural is touched.
    let i = head + 1;
    while (i < lines.length && (/^\s*#/.test(lines[i]) || lines[i].trim() === "")) i++;
    lines.splice(head + 1, i - head - 1, "");
  }
  const jobs = lines.findIndex((l) => /^jobs:\s*$/.test(l));
  for (let i = jobs + 1; i < lines.length; i++) {
    if (lines[i] === `  ${job}:`) {
      lines[i] = "  characterization:";
      break;
    }
  }
  return (
    `${MARKER} from .github/workflows/${name}.\n` +
    "#\n" +
    "# The repo's own test workflow, with the command changed. Its setup steps are\n" +
    "# copied verbatim BECAUSE they are the ones this repo needs - editing them here\n" +
    "# would make this file a second, drifting answer to how the repo builds.\n" +
    "#\n" +
    "# It exists because the repo's own `include` does not match the corpus, so the\n" +
    "# green check on a characterization pull request was true of the pre-existing\n" +
    "# suite and said nothing about the tests the pull request adds.\n" +
    "#\n" +
    "# Delete it and that is true again.\n" +
    `${lines.join("\n").replace(/\n{3,}$/, "\n")}`
  );
}

function main() {
  if (!existsSync(WORKFLOWS)) {
    process.stdout.write(
      `· no ${relative(REPO_ROOT, WORKFLOWS)} - this repo has no GitHub Actions, and nothing here creates one.\n` +
        `  The emitted corpus is NOT covered by any check.\n`
    );
    return;
  }
  const files = readdirSync(WORKFLOWS)
    .filter((f) => /\.ya?ml$/.test(f))
    .map((f) => ({ name: f, text: readFileSync(join(WORKFLOWS, f), "utf8") }));

  if (existsSync(TARGET) && !readFileSync(TARGET, "utf8").includes(MARKER)) {
    process.stdout.write(
      `· ${relative(REPO_ROOT, TARGET)} exists and is not this tool's - left alone.\n`
    );
    return;
  }

  const chosen = pick(files);
  if (!chosen.name) {
    process.stdout.write(
      `· no workflow to copy: ${chosen.reason ?? "none of them runs this repo's test script"}.\n` +
        `  The emitted corpus is NOT covered by any check. Add one, or say so in the pull request body.\n`
    );
    return;
  }

  const out = rewrite(chosen);
  if (!WRITE) {
    process.stdout.write(`· would write ${relative(REPO_ROOT, TARGET)} from ${chosen.name} (--write to do it)\n`);
    return;
  }
  mkdirSync(WORKFLOWS, { recursive: true });
  writeFileSync(TARGET, out);
  process.stdout.write(
    `✓ ${relative(REPO_ROOT, TARGET)} ← ${chosen.name}, running \`${COMMAND}\`\n` +
      `  a red corpus is now a red check on the pull request\n`
  );
}

if (import.meta.url === `file://${process.argv[1]}`) main();
