/**
 * Stage 4, provider rows — answered from what production actually observed.
 *
 * 40 rows are blocked on api.anthropic.com / api.openai.com. Reaching them for
 * real means billed requests on the Qode keys that live in staging's `api_key`
 * rows, and that was declined in favour of replaying the calls the service has
 * ALREADY made: 17,136 rows in `usage_log` / `usage_log_content`, of which 220
 * are failures across 17 distinct error shapes.
 *
 * This is not the same thing as a real call and the difference is worth stating
 * plainly:
 *
 *   - What it gives you is REAL. Every finish_reason, every error string, every
 *     null rate below came out of the database. Nothing here is invented, which
 *     is the property the whole pipeline is built to protect.
 *   - What it does not give you is TODAY. A shape that changed after the last
 *     matching call would go unnoticed. The capture is dated, and the generated
 *     fixture carries that date so a reader can see how stale it is.
 *
 * One limitation the log genuinely cannot settle: `usage_log.error_message` is
 * a string column, so a rejection is stored as its message whether the thrown
 * value was an `Error` or a bare string. The `err instanceof Error ? … : String(err)`
 * arms therefore still have no evidence for their FALSE side from this source.
 * Reported, not papered over.
 *
 * Read-only. SELECT only. No prompt text and no model output is captured -
 * shapes, counts, lengths and null rates, and error messages clipped.
 *
 *   node .claude/charpilot/providerreplay.mjs
 *     → test/fixtures/provider-observed.ts
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve, join, relative } from "node:path";

import { OUT_DIR, FIXTURES_DIR,
  PILOT_DIR, REPO_ROOT } from "./config.mjs";

const VOCAB = join(OUT_DIR, "provider-vocab.json");
const OUTPUT = join(FIXTURES_DIR, "provider-observed.ts");

/** Error messages are clipped, and one already arrives masked by OpenAI. */
const CLIP = 200;
const clip = (s) => (s.length > CLIP ? `${s.slice(0, CLIP)}…` : s);

/**
 * One recorded OpenAI 401 quotes the key back with everything after `sk-proj-`
 * replaced by asterisks - masked by OpenAI, not by us, so nothing secret is
 * there. The long asterisk run is collapsed anyway: it trips credential
 * scanners, and a scanner that cries wolf on a committed fixture is a scanner
 * people stop reading.
 */
const collapseMasked = (s) => s.replace(/\*{8,}/g, "<masked by the provider>");

/**
 * A recorded failure that ai-centralization produced ITSELF is not a provider
 * shape - the circuit breaker and the tool-translation guards are this
 * service's own messages, and answering a provider SDK with one would pin a
 * fiction. They are kept, labelled, because they ARE the real input to the
 * error-classification arms downstream of them.
 */
const SELF_INFLICTED = /^Circuit breaker \[|^Unsupported content block |^Gemini produced a malformed|^tool_result references unknown/;

function main() {
  if (!existsSync(VOCAB)) {
    process.stderr.write(
      `\nno ${relative(REPO_ROOT, VOCAB)}. Capture it first:\n  node .claude/charpilot/providervocab.mjs --env-file .claude/charpilot/out/staging.env\n`
    );
    process.exit(1);
  }
  const v = JSON.parse(readFileSync(VOCAB, "utf8"));

  // AN EMPTY VOCABULARY IS NOT A VOCABULARY, and it is now a file that exists.
  //
  // providervocab.mjs writes `{ empty: true, reason }` and exits 0 when the
  // probe finds no `usage_log` — a service that records no provider usage, which
  // is most of them. Generating from it would emit a fixture whose own docblock
  // says "every value here was read out of staging's usage_log" over zero rows:
  // a file that reads as evidence and is not, which is the fabrication this
  // pipeline exists to prevent. Refused the same way an absent file is.
  if (v.empty) {
    process.stderr.write(`\n${relative(REPO_ROOT, VOCAB)} is empty: ${v.reason}\nThere is nothing to replay.\n`);
    process.exit(1);
  }

  const providerErrors = [];
  const ownErrors = [];
  for (const e of v.errors ?? []) {
    const row = { provider: e.provider, rows: e.rows, message: collapseMasked(clip(String(e.message))) };
    (SELF_INFLICTED.test(row.message) ? ownErrors : providerErrors).push(row);
  }

  const finish = (v.finishReasons ?? []).map((f) => ({ value: f.finishReason, rows: f.rows }));
  const nulls = Object.fromEntries((v.nullRates ?? []).map((n) => [n.column, n.nullRate]));
  const totalRows = (v.outcomes ?? []).reduce((n, o) => n + o.rows, 0);

  const ts = `/**
 * GENERATED by .claude/charpilot/providerreplay.mjs — do not edit by hand.
 *
 * Every value here was read out of staging's \`usage_log\` / \`usage_log_content\`
 * on ${v.readAt}: ${totalRows} recorded provider calls, ${(v.errors ?? []).length} distinct error shapes.
 * It is REAL and it is DATED. A provider shape that changed after the last
 * matching call is not represented, and no value here was invented.
 *
 * ${(v.guarantee ?? "").replace(/\\n/g, " ")}
 */

/** Real \`finish_reason\` values, with how often production saw each. */
export const OBSERVED_FINISH_REASONS = ${JSON.stringify(finish, null, 2)} as const;

/**
 * Real provider failures. These came back from the provider.
 *
 * NOTE: \`usage_log.error_message\` is a string column, so these are the
 * MESSAGES production stored — the log cannot say whether the thrown value was
 * an \`Error\` or a bare string. A row that needs the non-Error side of
 * \`err instanceof Error ? … : String(err)\` gets no evidence from here.
 */
export const OBSERVED_PROVIDER_ERRORS = ${JSON.stringify(providerErrors, null, 2)} as const;

/**
 * Real failures this service produced itself — the circuit breaker, the
 * tool-translation guards. Not provider shapes, so never use one as an SDK
 * answer; they ARE the real input to the classification arms below them.
 */
export const OBSERVED_OWN_ERRORS = ${JSON.stringify(ownErrors, null, 2)} as const;

/**
 * Measured null rate per \`usage_log\` column.
 *
 * \`cache_write_tokens\` is null in ${((nulls.cache_write_tokens ?? 0) * 100).toFixed(3)}% of rows — not 100%. Roughly
 * ${Math.max(1, Math.round(totalRows * (1 - (nulls.cache_write_tokens ?? 1))))} row(s) in ${totalRows} take the other side, which is exactly the kind of
 * arm that reaches production untested.
 */
export const OBSERVED_NULL_RATES = ${JSON.stringify(nulls, null, 2)} as const;

/** Shape of \`output_text\`: how much of it production sees as JSON. */
export const OBSERVED_OUTPUT_TEXT = ${JSON.stringify(v.outputText ?? {}, null, 2)} as const;

/** \`input_messages\` is an array of \`{ role, content }\` — ${(v.inputMessages?.elementKeys ?? []).map((k) => `${k.key} seen ${k.seen}×`).join(", ")}. */
export const OBSERVED_INPUT_MESSAGES = ${JSON.stringify(v.inputMessages ?? {}, null, 2)} as const;

export const OBSERVED_AT = ${JSON.stringify(v.readAt)};
export const OBSERVED_CALL_COUNT = ${totalRows};
`;

  mkdirSync(FIXTURES_DIR, { recursive: true });
  writeFileSync(OUTPUT, ts);
  process.stdout.write(
    `\n✓ observed provider vocabulary → ${relative(REPO_ROOT, OUTPUT)}\n` +
      `    recorded calls              ${totalRows}\n` +
      `    provider error shapes       ${providerErrors.length}\n` +
      `    this service's own errors   ${ownErrors.length}   (never an SDK answer)\n` +
      `    finish_reason values        ${finish.length}\n` +
      `    captured at                 ${v.readAt}\n\n` +
      `  Real, and dated. It cannot show a shape that changed after the last matching call,\n` +
      `  and it cannot say whether a rejection was an Error or a string.\n`
  );
}

// Only when this file is the ENTRY POINT.
//
// 26 of the 40 tools here executed on import, so a tool that wanted to reuse
// another's helper triggered a full run of it instead - which happened three
// times in one session: importing exec.mjs to read one function overwrote
// exec-rows.json, importing record.mjs to check it loaded started a 366-row
// recording, and importing diversity.mjs for its shape signature ran the whole
// census AND consumed the caller's own --json argument.
// `import.meta.main` needs Node 24. On an older runtime it is undefined, and a
// bare truthiness test would then turn every tool here into a silent no-op -
// far worse than a crash, because a pipeline that runs and does nothing reports
// success. So the absence is an error, not a fallback.
if (import.meta.main === undefined) {
  throw new Error("charpilot requires Node >= 24: import.meta.main is unavailable on " + process.version);
}
if (import.meta.main) {
  main();
}