#!/usr/bin/env node
/**
 * Stage 2, self-check — does the entry recipe actually work?
 *
 * scan.mjs claims 107 functions can be invoked at their own id. That claim is
 * derived from AST shape and is worth nothing until something imports the module
 * and looks. This generates a throwaway spec that does exactly that, runs it
 * through vitest (so TS transform, path aliases and test/setup.ts mocks all
 * apply, same as stage 4 will see), and reports every recipe that does not hold.
 *
 *   node .claude/charpilot/verify.mjs
 *
 * Writes out/entry-verify.json. Exits non-zero if any recipe fails — a scan whose
 * entry recipes are wrong hands stage 4 a work list it cannot execute.
 */
import { spawnSync } from "node:child_process";
import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";

import { CONFIG_DIR, OUT_DIR, REPO_ROOT, SCAN_JSON } from "./config.mjs";

const SPEC_PATH = join(OUT_DIR, "entry-verify.test.ts");
const RESULT_PATH = join(OUT_DIR, "entry-verify.json");
const VERIFY_CONFIG = join(CONFIG_DIR, "vitest.verify.config.mts");

const shape = (f) => ({
  id: f.id,
  file: f.file,
  // The ABSOLUTE path, resolved here rather than in the generated spec.
  //
  // The spec imported `target.file` — `src/pricing.ts` — which is a bare
  // specifier, so whether it resolves depends entirely on the host's alias
  // configuration. This repo has `@/*` plus tsconfig-paths and it worked; on a
  // freshly onboarded repo with no aliases EVERY entry came back
  // `module-import-failed: Cannot find package 'src/pricing.ts'`, which reads
  // as a scan that cannot see the code rather than as a resolver mismatch.
  // An absolute fs path needs no resolver and no alias table.
  abs: resolve(REPO_ROOT, f.file),
  name: f.name,
  arms: f.arms.istanbul,
  entry: f.entry,
});

function loadTargets() {
  const scan = JSON.parse(readFileSync(SCAN_JSON, "utf8"));
  const functions = scan.functions;

  // Both directions. Verifying only the positives proves nothing about the work
  // list's size: a function wrongly marked unreachable is silently dropped from
  // stage 4, and nothing downstream ever notices.
  return {
    positives: functions.filter((f) => f.entry.reachable).map(shape),
    negatives: functions
      .filter((f) => !f.entry.reachable && f.entry.kind === "module-private")
      .filter((f) => !f.name.startsWith("<"))
      .map(shape),
  };
}

/**
 * The spec is generated, not hand-written, so it can never drift from scan.json.
 * It asserts nothing itself — it records what it found and lets this script judge,
 * so one unimportable module does not hide the other 100 results.
 */
function writeSpec(targets, negatives) {
  const spec = `// GENERATED by .claude/charpilot/verify.mjs — do not edit, do not commit.
import { writeFileSync } from "node:fs";
import { it } from "vitest";

const TARGETS = ${JSON.stringify(targets, null, 2)};
const NEGATIVES = ${JSON.stringify(negatives, null, 2)};
const RESULT_PATH = ${JSON.stringify(RESULT_PATH)};

const modules = new Map<string, { mod?: Record<string, unknown>; error?: string }>();

async function loadModule(file: string, abs?: string) {
  const cached = modules.get(file);
  if (cached) return cached;
  let loaded: { mod?: Record<string, unknown>; error?: string };
  try {
    // Absolute, so no alias table decides whether this resolves. Keyed on the
    // repo-relative path so the cache and the reported id still agree.
    loaded = { mod: (await import(/* @vite-ignore */ abs ?? file)) as Record<string, unknown> };
  } catch (err) {
    loaded = { error: err instanceof Error ? \`\${err.name}: \${err.message}\` : String(err) };
  }
  modules.set(file, loaded);
  return loaded;
}

// test/setup.ts mocks several modules, and vitest's mock proxy THROWS on any
// export the mock does not define. Every read of a module namespace has to be
// guarded, or one mocked module aborts the whole verification run.
function pick(holder: Record<string, unknown> | undefined, key: string) {
  if (!holder) return { value: undefined, shielded: false };
  try {
    return { value: holder[key], shielded: false };
  } catch (err) {
    return { value: undefined, shielded: true, detail: err instanceof Error ? err.message.slice(0, 140) : String(err) };
  }
}

function resolveClass(mod: Record<string, unknown>, entry: Record<string, any>) {
  return entry.classDefaultExport ? pick(mod, "default") : pick(mod, entry.className);
}

it("entry recipes from scan.json resolve to something callable", async () => {
  const results: unknown[] = [];

  for (const target of TARGETS) {
    const { mod, error } = await loadModule(target.file, target.abs);
    if (!mod) {
      results.push({ ...target, ok: false, failure: "module-import-failed", detail: error });
      continue;
    }

    const entry = target.entry as Record<string, any>;
    let value: unknown;
    let failure: string | undefined;
    let detail: string | undefined;
    let shielded = false;

    switch (entry.kind) {
      case "import-named": {
        const got = pick(mod, entry.symbol);
        value = got.value; shielded = got.shielded; detail = got.detail;
        if (value === undefined && !shielded) { failure = "symbol-missing"; detail = entry.symbol; }
        break;
      }

      case "import-default": {
        const got = pick(mod, "default");
        value = got.value; shielded = got.shielded; detail = got.detail;
        if (value === undefined && !shielded) failure = "default-export-missing";
        break;
      }

      case "import-named-property": {
        const holder = pick(mod, entry.symbol);
        if (holder.shielded) { shielded = true; detail = holder.detail; break; }
        if (holder.value === undefined) { failure = "symbol-missing"; detail = entry.symbol; break; }
        const got = pick(holder.value as Record<string, unknown>, entry.property);
        value = got.value; shielded = got.shielded; detail = got.detail;
        if (value === undefined && !shielded) { failure = "property-missing"; detail = entry.property; }
        break;
      }

      case "class-method":
      case "class-static": {
        const found = resolveClass(mod, entry);
        if (found.shielded) { shielded = true; detail = found.detail; break; }
        const klass = found.value as (new (...a: unknown[]) => unknown) | undefined;
        if (klass === undefined) { failure = "class-not-exported"; detail = entry.className; break; }
        if (entry.member === "constructor") { value = klass; break; }
        const got = entry.kind === "class-static"
          ? pick(klass as unknown as Record<string, unknown>, entry.member)
          : pick(klass.prototype as Record<string, unknown>, entry.member);
        value = got.value; shielded = got.shielded; detail = got.detail ?? detail;
        if (value === undefined && !shielded) { failure = "member-missing"; detail = entry.member; }
        break;
      }

      default:
        failure = "unknown-entry-kind";
        detail = entry.kind;
    }

    // A module replaced by a setup.ts mock cannot confirm or deny the recipe.
    // Reported separately — it is a fact about the harness, not about the scan.
    if (shielded) {
      results.push({ ...target, ok: false, failure: "mocked-in-setup", detail });
      continue;
    }

    if (!failure && typeof value !== "function") {
      failure = "not-callable";
      detail = \`typeof === \${typeof value}\`;
    }

    results.push({ ...target, ok: !failure, failure, detail });
  }

  // Falsify the other half: anything called "module-private" must genuinely not
  // be on the module's export surface. A trailing \"export { f }\" statement
  // exports without an inline modifier, and would otherwise be dropped silently.
  const falseNegatives: unknown[] = [];
  for (const target of NEGATIVES) {
    const { mod } = await loadModule(target.file, target.abs);
    if (!mod) continue;
    const got = pick(mod, target.name);
    if (!got.shielded && typeof got.value === "function") {
      falseNegatives.push({ ...target, exportedAs: target.name });
    }
  }

  writeFileSync(
    RESULT_PATH,
    JSON.stringify({ generatedAt: new Date().toISOString(), results, falseNegatives }, null, 2)
  );
});
`;
  writeFileSync(SPEC_PATH, spec);
}

function report(results, targets, falseNegatives, negatives) {
  const ok = results.filter((r) => r.ok);
  const shielded = results.filter((r) => r.failure === "mocked-in-setup");
  const bad = results.filter((r) => !r.ok && r.failure !== "mocked-in-setup");

  const byFailure = {};
  for (const r of bad) byFailure[r.failure] = (byFailure[r.failure] ?? 0) + 1;

  const armsOk = ok.reduce((n, r) => n + r.arms, 0);
  const armsBad = bad.reduce((n, r) => n + r.arms, 0);

  const lines = [
    "",
    `✓ entry verification → ${relative(REPO_ROOT, RESULT_PATH)}`,
    `    claimed reachable  ${targets.length}`,
    `    actually callable  ${ok.length} (${((ok.length / targets.length) * 100).toFixed(1)}%), covering ${armsOk} arms`,
    `    recipe wrong       ${bad.length}, holding ${armsBad} arms`,
    `    unverifiable       ${shielded.length} — module is mocked by test/setup.ts`,
    "",
    `    claimed private    ${negatives.length}`,
    `    wrongly excluded   ${falseNegatives.length} (exported after all, so stage 4 would have skipped them)`,
  ];

  for (const fn of falseNegatives.slice(0, 10)) {
    lines.push(`      exported: ${fn.id}`);
  }

  if (bad.length) {
    lines.push("", "  failures by kind:");
    for (const [k, n] of Object.entries(byFailure).sort((a, b) => b[1] - a[1])) {
      lines.push(`    ${String(n).padStart(4)}  ${k}`);
    }
    lines.push("", "  first 15:");
    for (const r of bad.slice(0, 15)) {
      lines.push(`    ${r.failure.padEnd(22)} ${r.id}${r.detail ? `  — ${r.detail}` : ""}`);
    }
    if (bad.length > 15) lines.push(`    … ${bad.length - 15} more (see the json)`);
  }

  process.stdout.write(`${lines.join("\n")}\n`);
  return bad.length === 0 && falseNegatives.length === 0;
}

function main() {
  mkdirSync(OUT_DIR, { recursive: true });
  const { positives, negatives } = loadTargets();
  if (positives.length === 0) throw new Error("no reachable functions in scan.json — run pilot:scan first");

  rmSync(RESULT_PATH, { force: true });
  writeSpec(positives, negatives);

  process.stdout.write(
    `· verifying ${positives.length} entry recipes and falsifying ${negatives.length} private claims …\n`
  );
  const run = spawnSync(
    "npx",
    ["vitest", "run", "--config", VERIFY_CONFIG, "--reporter=default"],
    { cwd: REPO_ROOT, encoding: "utf8" }
  );

  let payload;
  try {
    payload = JSON.parse(readFileSync(RESULT_PATH, "utf8"));
  } catch {
    throw new Error(
      `verification spec produced no results (exit ${run.status}).\n${(run.stderr || run.stdout || "").slice(-3000)}`
    );
  } finally {
    // The generated spec is throwaway. Leaving it behind would put a fake test
    // file in the repo, which is exactly the failure mode this pilot guards.
    rmSync(SPEC_PATH, { force: true });
  }

  if (!report(payload.results, positives, payload.falseNegatives ?? [], negatives)) process.exit(1);
}

// Guarded, like every other tool here, so importing this file is side-effect
// free. Without it the gate's `tools-parse` check - which IMPORTS each tool,
// because a parse check waves through a missing import - ran the whole
// verification as a side effect: 268 recipes and a vitest spawn, against a 30s
// timeout, reported as "verify.mjs: failed to load" on a repo where nothing was
// wrong with the file.
if (import.meta.main) {
  try {
    main();
  } finally {
    rmSync(SPEC_PATH, { force: true });
  }
}
