/**
 * (No shebang, like srcdir.mjs: a vitest config may reach this through a tool
 * module, and vitest 2's config bundler rejects a shebang in an import.)
 *
 * WHICH NODE THE REPO'S CI RUNS, AND THE BINARY HERE THAT IS THAT NODE (D54).
 *
 *   node cinode.mjs <repo> [--json]    prints the binary; --json the whole answer
 *
 * THE DEFECT. The image is node:24 and every tool spawned the target's vitest
 * with `process.execPath`, so every row was RECORDED under Node 24, and cigate,
 * the gate that exists so a delivered suite is never red in the repo it goes
 * to, ran it under Node 24 too. The repos' CI runs `actions/setup-node` with
 * `node-version: 20`. What the engine itself writes differs between the two,
 * and the recording pins it:
 *
 *   interview-service #102  "Bad escaped character in JSON at position 2 (line 1 column 3)"
 *                           recorded; Node 20 says "... at position 2". The
 *                           SyntaxError is wrapped in the service's own Error,
 *                           so engineStableMessage (which only rewrites a
 *                           SyntaxError's own message) cannot see it.
 *   ai-centralization #98   ERR_OSSL_UNSUPPORTED recorded with `opensslErrorStack`
 *                           (OpenSSL 3.5, Node 24); Node 20's OpenSSL 3.0 error
 *                           has no such field.
 *
 * Neither is normalisable in general - an engine difference can land anywhere
 * in a value - so the fix is not a better normaliser: the target is recorded
 * AND gated under the Node its CI runs.
 *
 * THE TOOLS STAY ON THE IMAGE'S NODE. 26 of them need `import.meta.main`
 * (Node >= 24.2) and refuse to run without it. What changes is the process
 * that runs the TARGET's code: the vitest record.mjs, cigate.mjs, coverage.mjs
 * and verify-generated.mjs spawn, and (docker/char/packs/common.py) the
 * `npm ci` that installs the repo - a native addon built under 24's ABI does
 * not load under 20's.
 *
 * WHERE THE MAJOR COMES FROM, in the order the CI itself would have it:
 *   1. `.github/workflows/*.yml` - `actions/setup-node`'s `node-version`, or
 *      the file its `node-version-file` names. The characterization check
 *      cicheck.mjs wrote wins, then a workflow that runs the test script, then
 *      any other; a `${{ matrix.x }}` / `${{ env.X }}` is looked up in the same
 *      file, and a matrix of several is its LOWEST major (the one furthest
 *      from the image, and a test green there is the one at risk);
 *   2. `.nvmrc`, then `.node-version`;
 *   3. `package.json` `engines.node` - the image's own major when the range
 *      admits it (an engines range is a constraint, not a pin), else the
 *      highest installed major it admits;
 *   4. the image's own Node.
 *
 * WHERE THE BINARY COMES FROM. The image's own major is `process.execPath`;
 * any other is `$CHARPILOT_NODE_ROOT/<major>/bin/node` (default /opt/node,
 * where docker/Dockerfile unpacks the official tarballs). A major the image
 * does not carry falls back to the image's Node and SAYS SO (`available:
 * false`, with why), because a run that silently records under another Node
 * is this defect again.
 *
 * `CHARPILOT_TARGET_NODE` overrides all of it: the nodejs pack resolves once
 * at container start, logs the answer and exports it, so every tool of the run
 * agrees on one binary.
 */
import { existsSync, readdirSync, readFileSync, realpathSync, statSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

export const NODE_ROOT_DEFAULT = "/opt/node";
const MARKER = "# GENERATED by .claude/charpilot/cicheck.mjs";
const RUNS_TESTS = /^\s*(?:-\s+)?run:\s*(?:npm|yarn|pnpm)\s+(?:run\s+)?test\b/m;
// setup-node's lts aliases, by codename.
const LTS = { argon: 4, boron: 6, carbon: 8, dubnium: 10, erbium: 12, fermium: 14, gallium: 16, hydrogen: 18, iron: 20, jod: 22, krypton: 24 };

const stripValue = (v) =>
  String(v ?? "")
    .replace(/\s+#.*$/, "")
    .trim()
    .replace(/^(['"])(.*)\1$/, "$2")
    .trim();

/**
 * The majors a version SPEC pins, or "latest" for one that asks for the newest
 * (`node`, `latest`, `current`, `lts/*`, `>=N` with no upper bound), or null
 * when it says nothing a major can be read from.
 */
export function specMajor(spec) {
  const s = stripValue(spec).toLowerCase();
  if (!s) return null;
  if (/^(node|latest|current|stable|lts\/\*|lts|\*)$/.test(s)) return "latest";
  const lts = s.match(/^lts\/([a-z]+)$/);
  if (lts) return LTS[lts[1]] ?? "latest";
  if (/^>=?\s*v?\d+/.test(s) && !/</.test(s)) return "latest";
  const m = s.match(/^[\^~=v\s]*(\d+)(?:\.|$|\s|x)/);
  return m ? Number(m[1]) : null;
}

/**
 * Whether an `engines.node` RANGE admits `major`, at major granularity: `>=18`,
 * `^20`, `20.x`, `>=18 <21`, `18 - 20`, `^18 || ^20`. Anything it cannot read
 * admits (an engines field that says nothing readable constrains nothing).
 */
export function rangeAdmits(range, major) {
  const alts = String(range ?? "").split("||").map((a) => a.trim());
  return alts.some((alt) => {
    if (!alt || alt === "*" || /^x$/i.test(alt)) return true;
    const hy = alt.match(/^v?(\d+)[.\dx*]*\s+-\s+v?(\d+)/i);
    if (hy) return major >= Number(hy[1]) && major <= Number(hy[2]);
    const parts = alt.split(/\s+/).filter(Boolean);
    return parts.every((p) => {
      const c = p.match(/^(>=|<=|>|<|=|\^|~)?v?(\d+)(\.[\dx*]+)*$/i);
      if (!c) return true;
      const n = Number(c[2]);
      const rest = c[3] ?? "";
      const minorGiven = /^\.\d/.test(rest) && !/^\.0(\.0)?$/.test(rest);
      switch (c[1]) {
        case ">=": return major >= n;
        case ">": return minorGiven ? major >= n : major > n;
        case "<": return minorGiven ? major <= n : major < n;
        case "<=": return major <= n;
        default: return major === n;
      }
    });
  });
}

/** The value a `${{ ctx.KEY }}` expression names, looked up in the same workflow text. */
function lookupExpression(text, expr) {
  const key = expr.match(/\$\{\{\s*(?:matrix|env|vars|inputs)\.([\w-]+)\s*\}\}/)?.[1];
  if (!key) return [];
  const lines = text.split("\n");
  const esc = key.replace(/[-]/g, "\\-");
  for (let i = 0; i < lines.length; i++) {
    const m = lines[i].match(new RegExp(`^(\\s*)(?:-\\s+)?['"]?${esc}['"]?:\\s*(.*)$`));
    if (!m) continue;
    const v = stripValue(m[2]);
    if (v.includes("${{")) continue;
    if (v.startsWith("[")) return v.replace(/^\[|\]$/g, "").split(",").map(stripValue).filter(Boolean);
    if (v) return [v];
    // A block list under the key.
    const out = [];
    for (let j = i + 1; j < lines.length; j++) {
      const li = lines[j].match(/^\s*-\s+(.*)$/);
      if (li) { out.push(stripValue(li[1])); continue; }
      if (lines[j].trim() === "" || /^\s*#/.test(lines[j])) continue;
      break;
    }
    if (out.length) return out;
  }
  return [];
}

/**
 * Every `actions/setup-node` step in one workflow's text, as the spec(s) it
 * asks for: `{ specs: [...], file: <node-version-file> | null, line }`.
 * Textual, like cicheck.mjs and for its reason: no YAML parser is a
 * dependency, and a step is a `- ` item whose lines are indented under it.
 */
export function setupNodeSteps(text) {
  const lines = String(text ?? "").split("\n");
  const indent = (l) => l.match(/^(\s*)/)[1].length;
  const out = [];
  for (let i = 0; i < lines.length; i++) {
    if (!/^\s*(?:-\s+)?uses:\s*['"]?actions\/setup-node@/.test(lines[i])) continue;
    // The step's own `- ` line: this one, or the nearest above it at a
    // shallower indent.
    let start = i;
    while (start >= 0 && !/^\s*-\s+/.test(lines[start])) start--;
    if (start < 0) start = i;
    const item = indent(lines[start]);
    let end = start + 1;
    while (end < lines.length) {
      const l = lines[end];
      if (l.trim() === "" || /^\s*#/.test(l)) { end++; continue; }
      if (indent(l) <= item) break;
      end++;
    }
    let version = null;
    let file = null;
    for (let j = start; j < end; j++) {
      const v = lines[j].match(/^\s*(?:-\s+)?node-version:\s*(.*)$/);
      if (v) version = stripValue(v[1]);
      const f = lines[j].match(/^\s*(?:-\s+)?node-version-file:\s*(.*)$/);
      if (f) file = stripValue(f[1]);
    }
    let specs = [];
    if (version && version.includes("${{")) specs = lookupExpression(text, version);
    else if (version && version.startsWith("[")) specs = version.replace(/^\[|\]$/g, "").split(",").map(stripValue).filter(Boolean);
    else if (version) specs = [version];
    out.push({ specs, expression: version && version.includes("${{") ? version : null, file, line: i + 1 });
  }
  return out;
}

/** The first line of a version file (.nvmrc, .node-version), or null. */
function versionFile(root, rel) {
  try {
    const t = readFileSync(resolve(root, rel), "utf8").split("\n").map((l) => l.replace(/#.*$/, "").trim()).find(Boolean);
    return t ?? null;
  } catch {
    return null;
  }
}

/** The majors installed under `nodeRoot`, plus the image's own. */
export function installedMajors({ nodeRoot = NODE_ROOT_DEFAULT, imageMajor = Number(process.versions.node.split(".")[0]) } = {}) {
  const out = new Set([imageMajor]);
  try {
    for (const d of readdirSync(nodeRoot)) {
      if (/^\d+$/.test(d) && existsSync(join(nodeRoot, d, "bin", "node"))) out.add(Number(d));
    }
  } catch { /* no extra runtimes */ }
  return [...out].sort((a, b) => a - b);
}

/**
 * WHICH MAJOR the repo's CI runs, and where that was read: `{ major, spec,
 * source }`, `major` null only when nothing says and the image's is used.
 */
export function ciNodeMajor(root, { imageMajor = Number(process.versions.node.split(".")[0]), installed = [imageMajor] } = {}) {
  const pick = (spec, source) => {
    const specs = Array.isArray(spec) ? spec : [spec];
    const majors = specs.map(specMajor).filter((m) => m !== null);
    if (!majors.length) return null;
    const nums = majors.map((m) => (m === "latest" ? imageMajor : m));
    const major = Math.min(...nums);
    return {
      major,
      spec: specs.join(", "),
      source: `${source}${specs.length > 1 ? ` (a matrix of ${specs.length}; its lowest major)` : ""}`,
    };
  };

  // 1. The workflows, the characterization check first.
  const dir = join(root, ".github", "workflows");
  let files = [];
  try {
    files = readdirSync(dir).filter((f) => /\.ya?ml$/.test(f)).map((f) => ({ name: f, text: readFileSync(join(dir, f), "utf8") }));
  } catch { /* no workflows */ }
  const rank = (f) => (f.text.includes(MARKER) ? 0 : RUNS_TESTS.test(f.text) ? 1 : 2);
  files.sort((a, b) => rank(a) - rank(b) || a.name.localeCompare(b.name));
  for (const f of files) {
    for (const step of setupNodeSteps(f.text)) {
      const where = `.github/workflows/${f.name}:${step.line} actions/setup-node`;
      if (step.specs.length) {
        const got = pick(step.specs, `${where} node-version${step.expression ? ` ${step.expression}` : ""}`);
        if (got) return got;
      }
      if (step.file) {
        const v = versionFile(root, step.file);
        const got = v && pick(v, `${where} node-version-file ${step.file}`);
        if (got) return got;
      }
    }
  }
  // 2. The version files.
  for (const rel of [".nvmrc", ".node-version"]) {
    const v = versionFile(root, rel);
    const got = v && pick(v, rel);
    if (got) return got;
  }
  // 3. engines.node - a constraint, so the image's own major when it is admitted.
  try {
    const range = JSON.parse(readFileSync(join(root, "package.json"), "utf8"))?.engines?.node;
    if (typeof range === "string" && range.trim()) {
      if (rangeAdmits(range, imageMajor)) return { major: imageMajor, spec: range, source: "package.json engines.node (admits the image's own Node)" };
      const admitted = installed.filter((m) => rangeAdmits(range, m));
      if (admitted.length) return { major: Math.max(...admitted), spec: range, source: "package.json engines.node (the highest installed major it admits)" };
      const got = pick(range, "package.json engines.node");
      if (got) return got;
    }
  } catch { /* no package.json, or not JSON */ }
  return { major: null, spec: null, source: "nothing in the repo names a Node version - the image's own" };
}

const CACHE = new Map();

/**
 * THE BINARY that runs the target's code: `{ node, major, spec, source,
 * available, why }`. Memoised per root: every spawn in a run asks it.
 */
export function targetNode({
  root = process.cwd(),
  env = process.env,
  nodeRoot = env.CHARPILOT_NODE_ROOT || NODE_ROOT_DEFAULT,
  execPath = process.execPath,
  imageMajor = Number(process.versions.node.split(".")[0]),
} = {}) {
  const key = JSON.stringify([root, env.CHARPILOT_TARGET_NODE ?? null, nodeRoot, execPath, imageMajor]);
  if (CACHE.has(key)) return CACHE.get(key);
  let answer;
  const forced = (env.CHARPILOT_TARGET_NODE ?? "").trim();
  if (forced && existsSync(forced)) {
    const m = forced.match(/\/(\d+)\/bin\/node$/);
    answer = { node: forced, major: m ? Number(m[1]) : forced === execPath ? imageMajor : null, spec: null, source: "CHARPILOT_TARGET_NODE", available: true, why: null };
  } else {
    const installed = installedMajors({ nodeRoot, imageMajor });
    const ci = ciNodeMajor(root, { imageMajor, installed });
    const major = ci.major ?? imageMajor;
    const candidate = major === imageMajor ? execPath : join(nodeRoot, String(major), "bin", "node");
    const available = existsSync(candidate);
    answer = {
      node: available ? candidate : execPath,
      major: available ? major : imageMajor,
      wanted: major,
      spec: ci.spec,
      source: ci.source,
      available,
      why: available
        ? null
        : `the repo's CI runs Node ${major} (${ci.source}) and this image carries no ${candidate} - the target runs under the image's Node ${imageMajor}, so an engine-written value in the recording can differ from what its CI prints`,
    };
    if (forced && !existsSync(forced)) answer.why = `CHARPILOT_TARGET_NODE=${forced} does not exist; ${answer.why ?? "resolved from the repo instead"}`;
  }
  CACHE.set(key, answer);
  return answer;
}

/**
 * `env` with the target Node's bin FIRST on PATH, so `npm`, `npx` and a
 * `#!/usr/bin/env node` script run under it too. Unchanged when the target
 * Node is this process's own.
 */
export function targetNodeEnv(env = process.env, t = targetNode()) {
  if (!t?.node || t.node === process.execPath) return { ...env };
  return { ...env, PATH: `${dirname(t.node)}:${env.PATH ?? ""}` };
}

/** One line for a log: which Node the target runs under, and why. */
export function targetNodeLine(t = targetNode()) {
  let v = "?";
  try { v = statSync(t.node) && t.node === process.execPath ? process.version : `v${t.major}`; } catch { /* not there */ }
  return `target Node ${v} (${t.node}) - ${t.source}${t.why ? ` - ${t.why}` : ""}`;
}

const isMain = () => {
  try { return Boolean(process.argv[1]) && realpathSync(fileURLToPath(import.meta.url)) === realpathSync(process.argv[1]); } catch { return false; }
};
if (isMain()) {
  const root = resolve(process.argv.slice(2).find((a) => !a.startsWith("--")) ?? process.cwd());
  const t = targetNode({ root });
  if (process.argv.includes("--json")) process.stdout.write(`${JSON.stringify(t)}\n`);
  else process.stdout.write(`${t.node}\n`);
}
